version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQLServer
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA
      - MSSQL_SA_PASSWORD
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: